// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuditLogSchema from '../models/drizzle/audit-log.model';
import * as AuthSchema from '../models/drizzle/auth.model';
import * as EmailLogSchema from '../models/drizzle/email-log.model';
import * as EmailTemplateSchema from '../models/drizzle/email-template.model';
import * as EnumSchema from '../models/drizzle/enum.model';
import * as MediaSchema from '../models/drizzle/media.model';
import * as RelationSchema from '../models/drizzle/relation.model';
import * as SecurityStoreSchema from '../models/drizzle/security-store.model';
import * as SmtpProviderSchema from '../models/drizzle/smtp-provider.model';
import * as SystemSchema from '../models/drizzle/system.model';

const schema = {
	...AuditLogSchema,
	...AuthSchema,
	...EmailLogSchema,
	...EmailTemplateSchema,
	...EnumSchema,
	...MediaSchema,
	...RelationSchema,
	...SecurityStoreSchema,
	...SmtpProviderSchema,
	...SystemSchema,
};

export default schema;
