// AUTO‑GENERATED by update‑schema.mjs. Do not edit by hand.

import * as AuthSchema from '../models/drizzle/auth.model';
import * as EmailTemplateSchema from '../models/drizzle/email-template.model';
import * as EnumSchema from '../models/drizzle/enum.model';
import * as MediaSchema from '../models/drizzle/media.model';
import * as RelationSchema from '../models/drizzle/relation.model';
import * as SystemSchema from '../models/drizzle/system.model';

const schema = {
	...AuthSchema,
	...EmailTemplateSchema,
	...EnumSchema,
	...MediaSchema,
	...RelationSchema,
	...SystemSchema,
};

export default schema;
